name: frp/frps

on:
  push:
    tags:
      - 'frp/frps@*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}

jobs:
  build-docker-image:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/*/frp/frps@})" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: frp/frps
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/frp-frps:latest
            ${{ env.IMAGE_NAME }}/frp-frps:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
